### ISSUE TITLE
WARN -- : Moneybird::Resource::Contact does not have an `version' attribute

### ISSUE THREAD

**Issue by StephanMeijer** [maartenvanvliet/moneybird#10]

**Comment by mvz** [comment]
@StephanMeijer can you give some more details? Is this a message that appears? When and where do you see it?

**Comment by maartenvanvliet** [comment]
It is a message that appears when the api returns an attribute that the gem does not currently know about. I'll look into this one.

**Comment by maartenvanvliet** [comment]
I see support for the `version` field is added in https://github.com/maartenvanvliet/moneybird/commit/d61931f22d63db744e46197cc7cad9f9f7d4a559#diff-a55bc8b9b1a125e3e6fce74d5922a064

Can you reproduce the issue with the latest version?
