### ISSUE TITLE
Nested attributes for creating sales invoices?

### ISSUE THREAD

**Issue by bobbyworx** [maartenvanvliet/moneybird#31]
Does not seem to be able to pass in nested attributes to sales_invoices create.

```
moneybird_administration.sales_invoices.create(
        reference: 'Mortgage',
        contact_id: contact_id,
	currency: 'EUR',
	details_attributes: [{description: "Rocking Chair", price: 200}]
)
```

Is it something that I'm doing wrong? Looking through the source code this should be good to go.

**Comment by mvz** [comment]
I think you need to use `details` instead of `details_attributes`. If that doesn't work, can you post the errors your getting here?

**Comment by jankeesvw** [comment]
Yes, it should be `details` this issue can be closed.

**Comment by maartenvanvliet** [comment]
Thanks for verifying!
