### ISSUE TITLE
How to link a booking to a financial mutation?

### ISSUE THREAD

**Issue by plindelauf** [maartenvanvliet/moneybird#34]
I'm puzzling over how to use the PATCH link_booking operation as described [here in the documentation](https://developer.moneybird.com/api/financial_mutations/#patch_financial_mutations_id_link_booking). It seems that this is not supported currently by this gem, but I hope to be proven wrong... ;)

**Comment by maartenvanvliet** [comment]
It's probably not implemented as I never had a need for it ;) 

PR's welcome :)
