### ISSUE TITLE
Support for Purchase Invoices

### ISSUE THREAD

**Issue by jenskanis** [maartenvanvliet/moneybird#4]
I would love to see support for Purchase Invoices. Is this currently on your roadmap?

https://developer.moneybird.com/api/documents_purchase_invoices/

**Comment by maartenvanvliet** [comment]
Hi

Should not be too hard to do, I'll try and look into it later this week. PR's are also welcome of course :)

**Comment by jenskanis** [comment]
You're right. Here is it #5

**Comment by maartenvanvliet** [comment]
I merged it
