### ISSUE TITLE
Uninitialized constant Moneybird::Service::PurchaseInvoice (NameError)

### ISSUE THREAD

**Issue by peterdk** [maartenvanvliet/moneybird#42]
I am trying to create a purchase invoice, but get a NameError.

`administration.purchase_invoices.create(contact_id: contact.id, reference: payout_report.period, date: invoice_date)`
`uninitialized constant Moneybird::Service::PurchaseInvoice (NameError)`

administration is not nil

**Comment by peterdk** [comment]
Shouldn't that be `Moneybird::Service::Document::PurchaseInvoice`?

**Comment by maartenvanvliet** [comment]
Could you write a failing test perhaps and file a PR?

**Comment by peterdk** [comment]
Yeah I can look into that. But can't get it working now.

```
invoice = Moneybird::Service::Document::PurchaseInvoice.new(contact.id,administration.id)
invoice.date = date  #undefined method `date=' for #<Moneybird::Service::Document::PurchaseInvoice:0x00000000055af2d0> (NoMethodError)
```
I know ruby, but I am not familiar with ActiveResource etc. So I don't know if it's because I am creating the PurchaseInvoice directly?

**Comment by peterdk** [comment]
I see a method administration.purchase_invoice_documents, which sort of works, but all requests fail with `/moneybird/middleware/error_handling.rb:21:in `on_complete': #<struct Faraday::Env method=:post, body="{\"error\":\"Purchase Invoice is required\`
It seems the parameters are not correct. When I try to set `purchase_invoice=data` it complains about not having that attribute. It seems the purchase invoices is not tested or so?

**Comment by maartenvanvliet** [comment]
It seems so, with a failing test I can look into it

**Comment by maartenvanvliet** [comment]
closing this for now
