### ISSUE TITLE
Support for download_pdf

### ISSUE THREAD

**Issue by mvz** [maartenvanvliet/moneybird#46]
Downloading PDFs for sales invoices is now supported via the download_pdf endpoint. Old hacks like using the `sales_invoice.url` property and appending `.pdf` no longer work.

It would be nice if this gem supported `download_pdf` on the `SalesInvoice` service.

I have tried implementing this, but got stuck because Faraday tries to parse all responses as json, and this endpoint does not return json (in fact, it returns a redirect with a plain text body).

I tried limiting the processing as json like so during the setup of the http client:
```
  faraday.response :json, content_type: /\bjson$/
```
However, this causes loads of tests to fail because the response mocks don't set the content type.

**Comment by maartenvanvliet** [comment]
Closing this with https://github.com/maartenvanvliet/moneybird/pull/62
