### ISSUE TITLE
Possibility to have a new version bump

### ISSUE THREAD

**Issue by LuukvH** [maartenvanvliet/moneybird#53]

**Comment by StefSchenkelaars** [comment]
@maartenvanvliet Would indeed be great if you could release a new version with the latest changes 👍

**Comment by maartenvanvliet** [comment]
Sure, will do sometime this week :)

**Comment by StefSchenkelaars** [comment]
Ping @maartenvanvliet 

Sorry to bother you but are the only owner on rubygems 🙂

**Comment by maartenvanvliet** [comment]
Thanks for the reminder, just pushed a release.

**Comment by StefSchenkelaars** [comment]
Thanks! 👍
