### ISSUE TITLE
Custom fields are not saved when creating an invoice

### ISSUE THREAD

**Issue by mvanduijker** [maartenvanvliet/moneybird#67]
reproduce: 
```ruby
client = Moneybird::Client.new('some token')
administration = client.administrations.find(administration_id).first
administration.sales_invoices.create({
  contact_id: some_contact_id,
  custom_fields: [
    {id: some_id, value: 'some value'}
  ]
})

```

After looking in Moneybird custom fields data does not appear to be filled in the invoice.

Building the invoice resource by hand, it does fill the custom_fields attribute but when calling the to_json method on the resulting object it gets serialised as custom_fields instead of custom_fields_attributes and ignored by Moneybird API.

```ruby
invoice = administration.sales_invoices.build({
  contact_id: some_contact_id,
  custom_fields: [
    {id: some_id, value: 'some value'}
  ]
})

pp invoice
pp invoice.to_json
```

I guess we have to add a custom_field resource to solve this problem.

**Comment by maartenvanvliet** [comment]
Yes seems like it 🙂. PR welcome!

**Comment by mvanduijker** [comment]
I see it's already implemented by https://github.com/maartenvanvliet/moneybird/pull/59 could you make a release?

**Comment by maartenvanvliet** [comment]
done! 🎉
