### ISSUE TITLE
PDF download stopped working with the released version of this gem

### ISSUE THREAD

**Issue by mvz** [maartenvanvliet/moneybird#82]
Since a few days, Moneybird returns a valid JSON body for the `download_pdf` endpoint (even though the response still has the `text/plain` mime type). Because of this, the `#download_pdf` method on sales invoices has stopped working with the latest released version of this gem, since the code there relies on a JSON parse error to occur.

I have tested with current `master` and it works, except that either Faraday 2.0.1 or later needs to be used, or a specific adapter must be installed and configured.

Perhaps it's time for a new release?

**Comment by maartenvanvliet** [comment]
Released! https://github.com/maartenvanvliet/moneybird/releases/tag/v0.10.2

thx!
